---
title: "SAT solver performance evaluation"
output: html_document
---

```{r}
library("tidyverse")
```

# Measurements

Cool stuff.

```{r}
results_warmup <- read_csv("results-warmup.csv", col_types = "i-n----fl")

results_warmup <- results_warmup %>%
    group_by(iteration, virtual, adjacency) %>%
    summarize(solve = mean(solve), .groups = "keep")

results_warmup %>%
    filter(!virtual) %>%
    ggplot(aes(x = iteration, y = solve, color = adjacency)) +
    geom_line()

results_warmup %>%
    filter(virtual) %>%
    ggplot(aes(x = iteration, y = solve, color = adjacency)) +
    geom_line()



results_perf <- read_csv("results-perf.csv", col_types = "n-f--n-fl")

results_perf <- results_perf %>%
    group_by(counter, virtual, adjacency) %>%
    summarize(value = mean(value), ratio = mean(ratio), .groups = "keep")



results_perf %>%
    filter(!virtual, counter == "cycles:u" | counter == "L1-dcache-loads:u" | counter == "branches:u") %>%
    ggplot(aes(fill = counter, x = value, y = adjacency)) +
    geom_bar(position = "dodge", stat = "identity")

results_perf %>%
    filter(!virtual, counter == "L1-dcache-load-misses:u" | counter == "branch-misses:u") %>%
    ggplot(aes(fill = counter, x = value, y = adjacency)) +
    geom_bar(position = "dodge", stat = "identity")

results_perf %>%
    filter(!virtual, counter == "page-faults:u") %>%
    ggplot(aes(fill = counter, x = value, y = adjacency)) +
    geom_bar(position = "dodge", stat = "identity")



results_perf %>%
    filter(adjacency == "vector", counter == "cycles:u" | counter == "L1-dcache-loads:u" | counter == "branches:u") %>%
    ggplot(aes(fill = counter, x = value, y = virtual)) +
    geom_bar(position = "dodge", stat = "identity")

results_perf %>%
    filter(adjacency == "vector", counter == "L1-dcache-load-misses:u" | counter == "branch-misses:u") %>%
    ggplot(aes(fill = counter, x = value, y = virtual)) +
    geom_bar(position = "dodge", stat = "identity")
```
