name: "Build"

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: |
        pwd
        ls        
        sudo apt-get update -y
        sudo apt-get update
        sudo apt-get -y install cmake ninja-build g++ git curl antlr4 libantlr4-runtime-dev
    - name: Configure
      run: |
        pwd
        ls
        cmake -S . -B build/ -G "Ninja Multi-Config" -DANTLR_ROOT:FILEPATH=/usr/share/java
    - name: Build
      run: |
        cmake --build build/ --config Release --target all
